# Source code:
# https://github.com/FIWARE/data-space-connector/blob/main/charts/data-space-connector/values.yaml


## Only for consumer role

keycloak:
  enabled: false

registration:
  enabled: false

## General configuration

dataSpaceConfig:
  # host name: dsconfig
  enabled: true
  serviceType: ClusterIP
  port: 3002
  supportedModels:
    - "https://raw.githubusercontent.com/smart-data-models/dataModel.Consumption/master/ConsumptionPoint/schema.json"
    - "https://raw.githubusercontent.com/smart-data-models/dataModel.Consumption/master/ConsumptionCost/schema.json"
  supportedProtocols:
    - http
    - https
  authenticationProtocols:
    - oid4vp


################################################################################
## CREDENTIALS/VERIFIERS (Services)
################################################################################

# Configuration to be shared between the authentication components 
# (mysql databases).
authentication:
  # should a password for the database connection of authentication components
  # be generated in the cluster
  generatePasswords:
    enabled: ${generate_passwords_enabled}
    # name of the secret to put the generated password into
    secretName: ${mysql_secret}

# Configuration for the mysql to be deployed as part of the connector, 
# see https://github.com/bitnami/charts/tree/main/bitnami/mysql for all options.
mysql:
  enabled: ${mysql_enabled}
  fullnameOverride: ${mysql_host_name}
  primary:
    persistence:
      enabled: false
  secondary:
    persistence:
      enabled: false
  auth:
    existingSecret: ${mysql_secret}
  initdbScripts:
    # scripts to be executed on db startup
    create.sql: |
      CREATE DATABASE ${mysql_tildb_name};
      CREATE DATABASE ${mysql_ccsdb_name};

# Configuration for the credentials-config-service to be deployed as part of the
# connector, see https://github.com/FIWARE/helm-charts/tree/main/charts/credentials-config-service
# for all options.
credentials-config-service:
  enabled: ${ccs_enabled}
  fullnameOverride: ${ccs_host_name}
  database:
    persistence: ${ccs_db_persistence}
    host: ${mysql_host_name}
    username: ${mysql_root_pass}
    name: ${mysql_ccsdb_name}
    existingSecret: 
      enabled: ${generate_passwords_enabled}
      name: ${mysql_secret}
      key: ${mysql_secret_key}

# Configuration for the trusted-issuers-list to be deployed as part of the 
# connector, see https://github.com/FIWARE/helm-charts/tree/main/charts/trusted-issuers-list
# for all options.
trusted-issuers-list:
  enabled: ${til_enabled}
  fullnameOverride: ${til_host_name}
  # only open for clean up in the tests
  ingress:
    til:
      enabled: ${til_ingress_enabled}
      annotations:
        kubernetes.io/ingress.class: ${ingress_class} 
        # forcing everything to use ssl
        ingress.kubernetes.io/ssl-redirect: "true"
        # example annotations, allowing cert-manager to automatically create tls-certs
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: ${til_domain}
          paths:
            - /
      # tls:
      #   - secretName: ${til_secret_tls}
      #     hosts:
      #       - ${til_domain}
  database:
    persistence: ${til_db_persistence}
    host: ${mysql_host_name}
    username: ${mysql_root_pass}
    name: ${mysql_tildb_name}
    existingSecret: 
      enabled: ${generate_passwords_enabled}
      name: ${mysql_secret}
      key: ${mysql_secret_key}

# Configuration to be shared between the issuance components.
issuance:
  generatePasswords:
    enabled: ${generate_passwords_enabled}
    secretName: ${iss_secret}

# Configuration for the did-helper, should only be used for demonstrational 
# deployments, see https://github.com/wistefan/did-helper
did:
  enabled: ${did_enabled}
  # fullnameOverride: ${did_host_name} NOT AVAILABLE, default name: did-helper
  ingress:
    enabled: ${did_ingress_enabled}
    annotations:
      kubernetes.io/ingress.class: ${ingress_class} 
      # forcing everything to use ssl
      ingress.kubernetes.io/ssl-redirect: "true"
      # example annotations, allowing cert-manager to automatically create tls-certs
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: ${did_domain}
        paths:
          - /
    # tls:
    #   - secretName: ${did_secret_tls}
    #     hosts:
    #       - ${did_domain}
  secret: ${iss_secret}
  serviceType: ClusterIP
  port: ${did_port}
  cert:
    country: DE
    state: SAXONY
    locality: Dresden
    organization: M&P Operations Inc.
    commonName: www.mp-operation.org

# Configuration for the vcverifier to be deployed as part of the connector, 
# see https://github.com/FIWARE/helm-charts/tree/main/charts/vcverifier for all options
vcverifier:
  enabled: ${vcv_enabled}
  fullnameOverride: ${vcv_host_name}
  ingress:
    enabled: ${vcv_ingress_enabled}
    annotations:
      kubernetes.io/ingress.class: ${ingress_class} 
      # forcing everything to use ssl
      ingress.kubernetes.io/ssl-redirect: "true"
      # example annotations, allowing cert-manager to automatically create tls-certs
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: ${vcv_domain}
        paths:
          - /
    # tls:
    #   - secretName: ${vcv_secret_tls}
    #     hosts:
    #       - ${vcv_domain}
  deployment:
    logging:
      level: DEBUG
    server:
      host: http://${vcv_domain}:8080
    ${vcv_host_name}:
      tirAddress: http://tir.ds-operator.local:8080/ # tir data space operator
      did: $${DID}
    configRepo:
      configEndpoint: http://${ccs_host_name}:8080
    alternativeConfig: /alternative-conf/server.yaml
    additionalVolumes:
      - name: did-material
        emptyDir: {}
      - name: alternative-conf
        emptyDir: {}
    additionalVolumeMounts:
      - name: alternative-conf
        mountPath: /alternative-conf
    initContainers:
      - name: get-did
        image: ubuntu
        command:
          - /bin/bash
        args:
          - -ec
          - |
            #!/bin/bash
            apt-get -y update; apt-get -y install wget; apt-get -y install gettext-base
            cd /did-material
            wget http://${did_host_name}:3002/did-material/did.env
            export $(cat /did-material/did.env)
            cp /original-conf/server.yaml /alternative-conf/server.yaml
            envsubst < /alternative-conf/server.yaml
        volumeMounts:
          - name: did-material
            mountPath: /did-material
          - name: config-volume
            mountPath: /original-conf
          - name: alternative-conf
            mountPath: /alternative-conf

      - name: register-at-tir
        image: ubuntu
        command:
          - /bin/bash
        args:
          - -ec
          - |
            #!/bin/bash
            source /did-material/did.env
            apt-get -y update; apt-get -y install curl
            curl -X 'POST' 'http://${til_operator_domain}:8080/issuer' -H 'Content-Type: application/json' -d "{\"did\": \"$${DID}\", \"credentials\": []}"
          # curl -X 'POST' 'http://tir.trust-anchor.svc.cluster.local:8080/issuer' -H 'Content-Type: application/json' -d "{\"did\": \"$${DID}\", \"credentials\": []}"
        volumeMounts:
          - name: did-material
            mountPath: /did-material


################################################################################
## PROXY
################################################################################

postgresql:
  generatePasswords:
    enabled: ${generate_passwords_enabled}
    secretName: ${postgresql_secret}
  
  enabled: ${postgresql_enabled}
  fullnameOverride: ${postgresql_host_name}
  # configure authentication to mysql
  auth:
    # name of the secret to take the passowrds from
    existingSecret: ${postgresql_secret}
    # key of the secrets inside the secret
    secretKeys:
      adminPasswordKey: ${postgresql_secrect_key_adminpass}
      userPasswordKey: ${postgresql_secrect_key_userpass}
  # configuration for the primary of the db
  primary:
    persistence:
      enabled: false
    # scripts to be run on intialization
    initdb:
      scripts:
        create.sh: |
          psql postgresql://postgres:$${POSTGRES_PASSWORD}@localhost:5432 -c "CREATE DATABASE ${postgresql_papdb_name};"
        # psql postgresql://postgres:$${POSTGRES_PASSWORD}@localhost:5432 -c "CREATE DATABASE keycloak;"
  readReplicas:
    persistence:
      enabled: false

# Configuration for the odrl-pap to be deployed as part of the connector, 
# see https://github.com/FIWARE/helm-charts/tree/main/charts/odrl-pap for all
# options.
odrl-pap:
  enabled: ${odrl_pap_enabled}
  fullnameOverride: ${odrl_pap_host_name}
  deployment:
    initContainers:
      - name: get-did
        image: ubuntu
        command:
          - /bin/bash
        args:
          - -ec
          - |
            #!/bin/bash
            apt-get -y update; apt-get -y install wget
            cd /did-material
            wget http://${did_host_name}:3002/did-material/did.env
        volumeMounts:
          - name: did-material
            mountPath: /did-material
    additionalVolumes:
      - name: did-material
        emptyDir: {}
    additionalVolumeMounts:
      - name: did-material
        mountPath: /did-material
    command:
      - /bin/sh
    args:
      - -ec
      - |
        #!/bin/sh
        source /did-material/did.env
        export GENERAL_ORGANIZATION_DID=$DID
        ./application -Dquarkus.http.host=0.0.0.0
  ingress:
    enabled: ${odrl_pap_ingress_enabled}
    annotations:
      kubernetes.io/ingress.class: ${ingress_class} 
      # forcing everything to use ssl
      ingress.kubernetes.io/ssl-redirect: "true"
      # example annotations, allowing cert-manager to automatically create tls-certs
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: ${odrl_pap_domain}
        paths:
          - /
    # tls:
    #   - secretName: ${odrl_pap_secret_tls}
    #     hosts:
    #       - ${odrl_pap_domain}
  database:
    username: postgres
    url: jdbc:postgresql://postgresql:5432/${postgresql_papdb_name}
    existingSecret:
      enabled: ${generate_passwords_enabled}
      name: ${postgresql_secret}
      key: ${postgresql_secrect_key_adminpass}

# Configuration for the open-policy-agent to be deployed as part of the connector
# fulfilling the role of the PDP, as a sidecar to apisix
opa:
  enabled: ${opa_enabled}
  resourceUrl: http://${odrl_pap_host_name}:8080/bundles/service/v1
  port: ${opa_port}
  # pull delays for the policies bundle
  policies:
    minDelay: 2
    maxDelay: 4
  # pull delays for the methods bundle
  methods:
    minDelay: 1
    maxDelay: 3
  # pull delays for the data bundle
  data:
    minDelay: 1
    maxDelay: 15

# Configuration for apisix to be deployed as part of the connector, 
# see https://github.com/bitnami/charts/tree/main/bitnami/apisix for all options.
apisix:
  enabled: ${apisix_enabled}
  fullnameOverride: ${apisix_host_name}
  image:
    debug: true
  controlPlane:
    enabled: true
  dashboard:
    enabled: false
  dataPlane:
    enabled: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: ${ingress_class} 
        # forcing everything to use ssl
        ingress.kubernetes.io/ssl-redirect: "true"
        # example annotations, allowing cert-manager to automatically create tls-certs
        kubernetes.io/tls-acme: "true"
      hostname: ${apisix_domain}
      # tls:
      #   - secretName: ${apisix_secret_tls}
      #     hosts:
      #       - ${apisix_domain}
      extraHosts:
        - name: ${apisix_api_domain}
          path: /
  catchAllRoute:
    enabled: false
  routes: |-
    - uri: /.well-known/openid-configuration
      host: ${apisix_domain}
      upstream:
        nodes:
          ${vcv_host_name}:3000: 1
        type: roundrobin
      plugins:
        proxy-rewrite:
          uri: /services/data-service/.well-known/openid-configuration
    - uri: /.well-known/data-space-configuration
      upstream:
        nodes:
          dsconfig:3002: 1
        type: roundrobin
      plugins:
        proxy-rewrite:
          uri: /.well-known/data-space-configuration/data-space-configuration.json
        response-rewrite:
          headers:
            set:
              content-type: application/json
    - uri: /*
      host: ${apisix_domain}
      upstream:
        nodes:
          ${scorpio_host_name}:9090: 1
        type: roundrobin
      plugins:
        openid-connect:
          bearer_only: true
          use_jwks: true
          client_id: data-service
          client_secret: unused
          ssl_verify: false
          discovery: http://${vcv_host_name}:3000/services/data-service/.well-known/openid-configuration
        opa:
          host: "http://localhost:8181"
          policy: policy/main
          with_body: true
    - uri: /.well-known/openid-configuration
      host: ${apisix_api_domain}
      upstream:
        nodes:
          ${vcv_host_name}:3000: 1
        type: roundrobin
      plugins:
        proxy-rewrite:
          uri: /services/tmf-api/.well-known/openid-configuration
    - uri: /*
      host: ${apisix_api_domain}
      upstream:
        nodes:
          tm-forum-api:8080: 1
        type: roundrobin
      plugins:
        openid-connect:
          bearer_only: true
          use_jwks: true
          client_id: contract-management
          client_secret: unused
          ssl_verify: false
          discovery: http://${vcv_host_name}:3000/services/tmf-api/.well-known/openid-configuration
        opa:
          host: "http://localhost:8181"
          policy: policy/main
          with_body: true

################################################################################
# BROKER
################################################################################

dataplane:
  generatePasswords:
    enabled: ${generate_passwords_enabled}
    secretName: ${postgis_secret}

# Configuration for the postgresql to be deployed as part of the connector, see 
# https://github.com/bitnami/charts/tree/main/bitnami/postgresql for all options
postgis:
  enabled: ${postgis_enabled}
  fullnameOverride: ${postgis_host_name}
  nameOverride: ${postgis_host_name}
  auth:
    existingSecret: ${postgis_secret}
    secretKeys:
      adminPasswordKey: ${postgis_secrect_key_adminpass}
      userPasswordKey: ${postgis_secrect_key_userpass}
  primary:
    persistence:
      enabled: false
    initdb:
      scripts:
        # psql postgresql://postgres:$(kubectl get secret ${postgis_secret} -o jsonpath="{.data.postgres-password}" | base64 --decode)@localhost:5432 -c "CREATE EXTENSION postgis;"
        enable.sh: |
          psql postgresql://postgres:$${POSTGRES_PASSWORD}@localhost:5432 -c "CREATE EXTENSION postgis;"
          psql postgresql://postgres:$${POSTGRES_PASSWORD}@localhost:5432 -c "CREATE DATABASE ngb;"
  readReplicas:
    persistence:
      enabled: false

# Configuration of the context-broker
# see https://github.com/FIWARE/helm-charts/tree/main/charts/scorpio-broker-aaio for details
scorpio:
  enabled: ${scorpio_enabled}
  fullnameOverride: ${scorpio_host_name}
  ingress:
    # only to make it available for the test initialization
    enabled: ${scorpio_ingress_enabled}
    annotations:
      kubernetes.io/ingress.class: ${ingress_class} 
      # forcing everything to use ssl
      ingress.kubernetes.io/ssl-redirect: "true"
      # example annotations, allowing cert-manager to automatically create tls-certs
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: ${scorpio_domain}
        paths:
          - /
    # tls:
    #   - secretName: ${scorpio_secret_tls}
    #     hosts:
    #       - ${scorpio_domain}
  # configuration of the database to be used by broker
  db:
    dbhost: ${postgis_host_name}
    user: ${postgis_db_username}
    existingSecret:
      enabled: ${generate_passwords_enabled}
      name: ${postgis_secret}
      key: ${postgis_secrect_key_adminpass}
  # configuration to register the dataplane at the credentials-config-service
  ccs:
    endpoint: http://${ccs_host_name}:8080
    configMap: scorpio-registration
    id: data-service
    defaultOidcScope:
      name: default
    oidcScopes:
      default:
        - type: UserCredential
          trustedParticipantsLists:
            - http://${til_operator_domain}:8080
          trustedIssuersLists:
            - http://${til_host_name}:8080
      operator:
        - type: OperatorCredential
          trustedParticipantsLists:
            - http://${til_operator_domain}:8080
          trustedIssuersLists:
            - http://${til_host_name}:8080


## TODO: MARKETPLACE
################################################################################

## configuration of the tm-forum-api - see https://github.com/FIWARE/helm-charts/tree/main/charts/tm-forum-api for details
tm-forum-api:
  # should it be enabled? set to false if one outside the chart is used.
  enabled: false
  # enable the api proxy
  apiProxy:
    enabled: false
  # redis caching
  redis:
    enabled: false

  registration:
    enabled: false

## configuration of the tm-forum-api - see https://github.com/FIWARE/helm-charts/tree/main/charts/contract-management for details
contract-management:
  enabled: false
