fullnameOverride: ${service_name}

deployment:
  additionalAnnotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8000'

#* Configuration for the orion-ld service
broker:
  port: ${orion_port}
  db:
    # The db to use. if running in multiservice mode, its used as a prefix.
    name: ${orion_db_name}
    auth: 
      user: root
      password: ${root_password}
      mech: "SCRAM-SHA-1"
    # Configuration of the mongo-db hosts. if multiple hosts are inserted,
    # its assumed that mongo is running as a replica set
    hosts:
      - ${mongo_service}        

#* Configuration for embedding mongodb into the chart. Do not use this in production.
mongo:
  enabled: false