deployment:
  image:
    repository: quay.io/i4trust/pdc-portal
    tag: 2.8.1
    pullPolicy: Always
  livenessProbe:
    initialDelaySeconds: 4
  readinessProbe:
    initialDelaySeconds: 5

route:
  enabled: false
  # host: onboarding-portal.dsba.fiware.dev
  # tls:
  #   termination: edge
  #   insecureEdgeTerminationPolicy: Redirect
  # # should a certificate for the address automatically be generated
  # certificate:
  #   issuer:
  #     kind: ClusterIssuer
  #     name: letsencrypt-aws-prod
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # forcing everything to use ssl
    ingress.kubernetes.io/ssl-redirect: "true"
    # example annotations, allowing cert-manager to automatically create tls-certs
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: ${ds_domain}
      paths:
      - /
  # configure the ingress' tls
  tls:
    - secretName: ${secret_tls_name}
      hosts:
        - ${ds_domain}

debug:
  enabled: true

ccs:
  endpoint: "${css_service}:8080/"
  # id: "4972b082-c3db-414c-afb7-bf48f2fc42f6"
  # credentials:
  #   - type: "VerifiableCredential"
  #     trustedParticipantsLists: [
  #       "https://tir.dsba.fiware.dev"
  #     ]
  #     trustedIssuersLists: [ #! What is this?
  #       "http://dsba-onboarding-portal-til-trusted-issuers-list:8080"
  #     ]

config:
  title: "OnBoarding Portal"
  getLabel: "Get Participants"
  inputLabel: "Participant"

  external:
    host: ${ds_domain}

  oidc:
    redirect_path: "/openid_connect1.0/return"
    acr: "urn:http://eidas.europa.eu/LoA/NotNotified/high"

  cb:
    endpoint: "${kong_service}/vc/ngsi-ld/v1"
    endpoint_siop: "${kong_service}/vc/ngsi-ld/v1"
  
  express:
    port: 7000

      
  # Configuration for SIOP flow
  siop:
    # SIOP flow enabled
    enabled: true
    # Base uri of the verifier
    verifier_uri: ${verifier_service}
    # # DID of verifier
    # did: "did:web:onboarding.dsba.fiware.dev:did"
    # # Client ID to be used
    # client_id: 4972b082-c3db-414c-afb7-bf48f2fc42f6

  idp: []
