fullnameOverride: ${service_name}

# initialParticipants: 
#   - did:web:packetdelivery.dsba.fiware.dev:did
#   - did:web:onboarding.dsba.fiware.dev:did
#   - did:web:happypets.dsba.fiware.dev:did
trustedparticipantsregistry:
  replicaCount: 1

  deployment:
    image:
      tag: 0.6.0
      pullPolicy: Always
    additionalLabels:
      participant: onboarding
  
  route:
    enabled: false
  
  #* Ingress configuration (should there be an ingress to connect the activation
  #* service with the public internet)
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      # forcing everything to use ssl
      ingress.kubernetes.io/ssl-redirect: "true"
      # example annotations, allowing cert-manager to automatically create tls-certs
      kubernetes.io/tls-acme: "true"
    hosts:
      # in fiware example it's: onboarding.dsba.fiware.dev (localhost by default)
      - host: ${ds_domain}
        paths:
        - /
    # configure the ingress' tls
    tls:
      - secretName: ${secret_tls_name}
        hosts:
          - ${ds_domain}

  tir:
    ngsiBroker:
      # URL of the NGSI LD broker.
      url: http://${orion_service_name}:1026/
      # Path to the API.
      path: ngsi-ld/v1
      # Timeout to apply when communicating with broker.
      timeout: 30s
      # Context file to be used in NGSI LD
      contextUrl: "https://registry.lab.gaia-x.eu/development/api/trusted-shape-registry/v1/shapes/jsonld/trustframework#"
    
    # satellite: #! What is this??
    #   id: "EU.EORI.FIWARESATELLITE"
    #   # Private key of satellite
    #   key: |
    #     -----BEGIN RSA PRIVATE KEY-----
    #     <Satellite private key>
    #     -----END RSA PRIVATE KEY-----
    #   # Certificate chain of satellite
    #   certificate: |
    #     -----BEGIN CERTIFICATE-----
    #     <Satellite certificate>
    #     -----END CERTIFICATE-----
    #     -----BEGIN CERTIFICATE-----
    #     <Intermediate certificates>
    #     -----END CERTIFICATE-----
    #     -----BEGIN CERTIFICATE-----
    #     <Root CA certificate>
    #     -----END CERTIFICATE-----
    #   # Configuration of CA trusted list
    #   trustedList:
    #     - name: FIWARE_CA
    #       crt: |
    #         -----BEGIN CERTIFICATE-----
    #         <FIWARETEST-CA Certificate>
    #         -----END CERTIFICATE-----
    #   # # Configuration of parties (trusted participants) - EXAMPLE
    #   # parties:
    #   #   - id: "EU.EORI.NLPACKETDEL"
    #   #     name: "Packet Delivery Company"
    #   #     status: "Active"
    #   #     start_date: "2021-09-27T00:00:00Z"
    #   #     end_date: "2051-09-27T00:00:00Z"
    #   #     crt: |
    #   #       -----BEGIN CERTIFICATE-----
    #   #       <Packet Delivery Company Certificate>
    #   #       -----END CERTIFICATE-----
    #   #     capability_url: "https://idp.packetdel.com/capabilities" # Optional
    #   #     certifications: # Optional
    #   #       - role: "IdentityProvider"
    #   #         start_date: "2021-09-27T00:00:00Z"
    #   #         end_date: "2051-09-27T00:00:00Z"
    #   #         loa: 3
    
    additionalConfigs:
      logger:
        levels:
          ROOT: ERROR
          org.fiware.iam: DEBUG
