# Ingress configuration
ingress:
    enabled: true
    annotations:
        kubernetes.io/ingress.class: "nginx"
        # forcing everything to use ssl
        ingress.kubernetes.io/ssl-redirect: "true"
        # example annotations, allowing cert-manager to automatically create tls-certs
        kubernetes.io/tls-acme: "true"
    hosts:
      - host: ${ds_domain}
        paths:
        - /
    # configure the ingress' tls
    tls:
      - secretName: ${secret_tls_name}
        hosts:
          - ${ds_domain}
deployment:
  image:
    repository: quay.io/fiware/vcverifier
    tag: 2.7.0-pre-26
    pullPolicy: Always
  logging: 
    level: DEBUG
    pathsToSkip: 
      - "/health"
  server:
    host: https://${ds_domain}
  ssikit: #! What is this??
    auditorUrl: http://${waltid_service}:7003
  verifier:
    tirAddress: https://${tpr_service}/v3/issuers
    # did: did:web:onboarding.dsba.fiware.dev:did
  # m2m: #! What is this??
  #   authEnabled: true
  #   keyPath: /opt/did/secret/tls.key
  #   credentialPath: /opt/credential/c127.0.0.1       waltid.ds-operator.ioredential.json
  #   clientId: tir-res
  #   verificationMethod: did:web:onboarding.dsba.fiware.dev:did#54134df8357d4aaea1e600f3d0ebe7fb
  configRepo:
    configEndpoint: http://${ccs_service}:8080/
  # initContainers: #! What is this??
  #   - name: load-did
  #     image: quay.io/opencloudio/curl:4.2.0-build.8
  #     imagePullPolicy: Always
  #     command: 
  #       - /bin/sh
  #       - /opt/did/script/import.sh
  #     env:
  #       - name: WALTID_CORE_ADDRESS
  #         value: "${waltid_service}:7000"
  #     # volumeMounts:
  #     #   - name: dsba-onboarding-did-config
  #     #     mountPath: /opt/did/script
  #     #   - name: did-secret
  #     #     mountPath: /opt/did/secret
  # # additionalVolumeMounts:
  # #   - name: ${service_name}
  # #     mountPath: /opt/credential
  # #   - name: did-secret
  # #     mountPath: /opt/did/secret
  # # additionalVolumes:
  # #   - name: ${namespace}-did-config
  # #     configMap:
  # #       name: ${namespace}-did-config
  # #   - name: ${service_name}
  # #     configMap:
  # #       name: ${service_name}
  # #   # - name: did-secret
  # #   #   secret: 
  # #   #     secretName: dsba-onboarding-portal-verifier-vcverifier-tls-sec