fullnameOverride: ${service_name}

# OpenShit route configuration
route:
  enabled: false

#* Ingress configuration (should there be an ingress to connect the activation service
#* with the public internet)
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # forcing everything to use ssl
    ingress.kubernetes.io/ssl-redirect: "true"
    # example annotations, allowing cert-manager to automatically create tls-certs
    kubernetes.io/tls-acme: "true"
  hosts:
    # in fiware example it's: onboarding.dsba.fiware.dev (localhost by default)
    - host: ${service_domain}
      paths:
      - /
  # configure the ingress' tls
  tls:
    - secretName: ${secret_tls_name}
      hosts:
        - ${service_domain}

did: ${did_domain}

#* Walt-id config
deployment:
  replicaCount: 1
  revisionHistoryLimit: 3
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  image:
    repository: quay.io/fiware/waltid
    tag: 1.14.1-SNAPSHOT
    pullPolicy: Always
persistence: 
  enabled: true
  pvc:
    size: 1Gi
api:
  ############################################################################
  #* CORE API configuration
  ############################################################################
  core: 
    enabled: true
    port: 7000
  ############################################################################
  #* SIGNATORY API configuration
  ############################################################################
  signatory: 
    enabled: true
    port: 7001
  ############################################################################
  #* AUDITOR API configuration
  ############################################################################
  auditor: 
    enabled: true
    port: 7002
  ############################################################################
  #* CUSTODIAN API configuration
  ############################################################################
  custodian:
    enabled: true
    port: 7003
  ############################################################################
  #* ESSIF API configuration
  ############################################################################
  essif:
    enabled: true
    port: 7010

#* VC templates to be used by waltId
templates: #! What is this??
  GaiaXParticipantCredential.json: |
    {
      "@context": [
        "https://www.w3.org/2018/credentials/v1",
        "https://registry.lab.dsba.eu/development/api/trusted-shape-registry/v1/shapes/jsonld/trustframework#"
      ],
      "type": [
        "VerifiableCredential"
      ],
      "id": "did:web:raw.githubusercontent.com:egavard:payload-sign:master",
      "issuer": "did:web:raw.githubusercontent.com:egavard:payload-sign:master",
      "issuanceDate": "2023-03-21T12:00:00.148Z",
      "credentialSubject": {
        "id": "did:web:raw.githubusercontent.com:egavard:payload-sign:master",
        "type": "gx:LegalParticipant",
        "gx:legalName": "dsba compliant participant",
        "gx:legalRegistrationNumber": {
          "gx:vatID": "MYVATID"
        },
        "gx:headquarterAddress": {
          "gx:countrySubdivisionCode": "BE-BRU"
        },
        "gx:legalAddress": {
          "gx:countrySubdivisionCode": "BE-BRU"
        },
        "gx-terms-and-conditions:gaiaxTermsAndConditions": "70c1d713215f95191a11d38fe2341faed27d19e083917bc8732ca4fea4976700"
      }
    }

#? not configured in the fiware example: https://github.com/FIWARE-Ops/fiware-gitops/blob/master/aws/dsba/onboarding-portal/walt-id/values.yaml
# config:
