fullnameOverride: ${service_name}

deployment:
  image: 
    repository: quay.io/fiware/credentials-config-service
    tag: 1.0.1

database:
  persistence: true
  host: ${mysql_service}
  name: ${ccs_db}
  username: root
  password: ${root_password}