fullnameOverride: ${service_name}

auth:
  rootPassword: ${root_password}

initdbScripts:
  create.sql: |
    CREATE DATABASE ${til_db};
    CREATE DATABASE ${ccs_db};

# rbac:  “Role-Based Access Control” (Control de Acceso Basado en Roles).
#   create: true
#   rules:
#     - apiGroups:
#       - security.openshift.io
#       resourceNames:
#       - anyuid
#       resources:
#       - securitycontextconstraints
#       verbs:
#       - use    
