fullnameOverride: ${service_name}

auth:
  enablePostgresUser: true
  postgresPassword: ${root_password}
  username: ${username} 
  password: ${password}
  # existingSecret: postgres-secret
  # secretKeys:
  #   adminPasswordKey: postgres-root-password
  #   userPasswordKey: postgres-password

primary:
  persistence:
    size: 2Gi
  initdb:
    scripts:
      enable.sh: |
        psql postgresql://postgres:${root_password}@localhost:5432 -c "CREATE EXTENSION postgis;"
        psql postgresql://postgres:${root_password}@localhost:5432 -c "CREATE DATABASE ${database_name};"

# rbac:
#   create: true
#   rules:
#     - apiGroups:
#       - security.openshift.io
#       resourceNames:
#       - anyuid
#       resources:
#       - securitycontextconstraints
#       verbs:
#       - use