# did: did:web:marketplace.dsba.fiware.dev:did
fullnameOverride: ${service_name}

route:
  enabled: false

#! NOT WORKING!!
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # forcing everything to use ssl
    ingress.kubernetes.io/ssl-redirect: "true"
    # example annotations, allowing cert-manager to automatically create tls-certs
    kubernetes.io/tls-acme: "true"
  hosts:
    # in fiware example it's: onboarding.dsba.fiware.dev (localhost by default)
    - host: ${dns_names}
      paths:
      - /
  # configure the ingress' tls
  tls:
    - secretName: ${secret_tls_name}
      hosts:
        - ${dns_names}

deployment:
  replicaCount: 1
  revisionHistoryLimit: 3
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  # image:  
  #   repository: waltid/ssikit
  #   tag: 1.2311262046.fix-didwebpath
  #   pullPolicy: Always
persistence: 
  enabled: true
  pvc:
    size: 1Gi
api:
  ############################################################################
  #* CORE API configuration
  ############################################################################
  core: 
    enabled: true
    port: 7000
  ############################################################################
  #* SIGNATORY API configuration
  ############################################################################
  signatory: 
    enabled: true
    port: 7001
  ############################################################################
  #* AUDITOR API configuration
  ############################################################################
  auditor: 
    enabled: true
    port: 7002
  ############################################################################
  #* CUSTODIAN API configuration
  ############################################################################
  custodian:
    enabled: true
    port: 7003
  ############################################################################
  #* ESSIF API configuration
  ############################################################################
  essif:
    enabled: true
    port: 7010

#* VC templates to be used by waltId
# templates: #! What is this??
#   ActivationService.json: |
#     {
#       "@context": ["https://www.w3.org/2018/credentials/v1"],
#       "credentialSchema": {
#         "id": "https://raw.githubusercontent.com/FIWARE-Ops/i4trust-provider/main/docs/schema.json",
#         "type": "FullJsonSchemaValidator2021"
#       },
#       "credentialSubject": {
#         "id": "did:ebsi:2AEMAqXWKYMu1JHPAgGcga4dxu7ThgfgN95VyJBJGZbSJUtp",
#         "roles": [{
#           "names": ["CREATE_ISSUER"],
#           "target": "did:elsi:packetdelivery"
#         }]
#       },
#       "id": "urn:uuid:3add94f4-28ec-42a1-8704-4e4aa51006b4",
#       "issued": "2021-08-31T00:00:00Z",
#       "issuer": "did:ebsi:2A9BZ9SUe6BatacSpvs1V5CdjHvLpQ7bEsi2Jb6LdHKnQxaN",
#       "validFrom": "2021-08-31T00:00:00Z",
#       "issuanceDate": "2021-08-31T00:00:00Z",
#       "type": ["VerifiableCredential", "ActivationService"]
#     }
#   IpsActivationService.json: |
#     {
#       "@context": ["https://www.w3.org/2018/credentials/v1"],
#       "credentialSchema": {
#         "id": "https://raw.githubusercontent.com/FIWARE-Ops/i4trust-provider/main/docs/schema.json",
#         "type": "FullJsonSchemaValidator2021"
#       },
#       "credentialSubject": {
#         "id": "did:ebsi:2AEMAqXWKYMu1JHPAgGcga4dxu7ThgfgN95VyJBJGZbSJUtp",
#         "roles": [{
#           "names": ["CREATE_ISSUER"],
#           "target": "did:elsi:ips"
#         }]
#       },
#       "id": "urn:uuid:3add94f4-28ec-42a1-8704-4e4aa51006b4",
#       "issued": "2021-08-31T00:00:00Z",
#       "issuer": "did:ebsi:2A9BZ9SUe6BatacSpvs1V5CdjHvLpQ7bEsi2Jb6LdHKnQxaN",
#       "validFrom": "2021-08-31T00:00:00Z",
#       "issuanceDate": "2021-08-31T00:00:00Z",
#       "type": ["VerifiableCredential", "IpsActivationService"]
#     }
#   OuranosActivationService.json: |
#     {
#       "@context": [
#         "https://www.w3.org/2018/credentials/v1"
#       ],
#       "credentialSchema": {
#         "id": "https://raw.githubusercontent.com/FIWARE-Ops/i4trust-provider/main/docs/schema.json",
#         "type": "FullJsonSchemaValidator2021"
#       },
#       "credentialSubject": {
#         "id": "did:ebsi:2AEMAqXWKYMu1JHPAgGcga4dxu7ThgfgN95VyJBJGZbSJUtp",
#         "roles": [
#           {
#             "names": [
#               "CREATE_ISSUER"
#             ],
#             "target": "did:web:ouranos-ws.com"
#           }
#         ]
#       },
#       "id": "urn:uuid:3add94f4-28ec-42a1-8704-4e4aa51006b4",
#       "issued": "2021-08-31T00:00:00Z",
#       "issuer": "did:ebsi:2A9BZ9SUe6BatacSpvs1V5CdjHvLpQ7bEsi2Jb6LdHKnQxaN",
#       "validFrom": "2021-08-31T00:00:00Z",
#       "issuanceDate": "2021-08-31T00:00:00Z",
#       "type": [
#           "VerifiableCredential",
#           "OuranosActivationService"
#       ]
#     }
#   MecaconnectActivationService.json: |
#     {
#       "@context": [
#         "https://www.w3.org/2018/credentials/v1"
#       ],
#       "credentialSchema": {
#         "id": "https://raw.githubusercontent.com/FIWARE-Ops/i4trust-provider/main/docs/schema.json",
#         "type": "FullJsonSchemaValidator2021"
#       },
#       "credentialSubject": {
#         "id": "did:ebsi:2AEMAqXWKYMu1JHPAgGcga4dxu7ThgfgN95VyJBJGZbSJUtp",
#         "roles": [
#           {
#             "names": [
#               "CREATE_ISSUER"
#             ],
#             "target": "did:web:sparep.mecaconnect.com"
#           }
#         ]
#       },
#       "id": "urn:uuid:3add94f4-28ec-42a1-8704-4e4aa51006b4",
#       "issued": "2021-08-31T00:00:00Z",
#       "issuer": "did:ebsi:2A9BZ9SUe6BatacSpvs1V5CdjHvLpQ7bEsi2Jb6LdHKnQxaN",
#       "validFrom": "2021-08-31T00:00:00Z",
#       "issuanceDate": "2021-08-31T00:00:00Z",
#       "type": [
#           "VerifiableCredential",
#           "MecaconnectActivationService"
#       ]
#     }
#   M2MTirCredential.json: |
#     {
#       "@context": [
#         "https://www.w3.org/2018/credentials/v1"
#       ],
#       "credentialSubject": {
#         "id": "did:ebsi:2AEMAqXWKYMu1JHPAgGcga4dxu7ThgfgN95VyJBJGZbSJUtp",
#         "roles": [
#           {
#             "names": [
#               "CREATE_ISSUER"
#             ],
#             "target": "did:web:somware.space"
#           }
#         ]
#       },
#       "id": "urn:uuid:3add94f4-28ec-42a1-8704-4e4aa51006b4",
#       "issued": "2021-08-31T00:00:00Z",
#       "issuer": "did:ebsi:2A9BZ9SUe6BatacSpvs1V5CdjHvLpQ7bEsi2Jb6LdHKnQxaN",
#       "validFrom": "2021-08-31T00:00:00Z",
#       "issuanceDate": "2021-08-31T00:00:00Z",
#       "type": [
#           "VerifiableCredential"
#       ]
#     }
#   SomwareActivationService.json: |
  #     {
  #       "@context": [
  #         "https://www.w3.org/2018/credentials/v1"
  #       ],
  #       "credentialSchema": {
  #         "id": "https://raw.githubusercontent.com/FIWARE-Ops/i4trust-provider/main/docs/schema.json",
  #         "type": "FullJsonSchemaValidator2021"
  #       },
  #       "credentialSubject": {
  #         "id": "did:ebsi:2AEMAqXWKYMu1JHPAgGcga4dxu7ThgfgN95VyJBJGZbSJUtp",
  #         "roles": [
  #           {
  #             "names": [
  #               "CREATE_ISSUER"
  #             ],
  #             "target": "did:web:somware.space"
  #           }
  #         ]
  #       },
  #       "id": "urn:uuid:3add94f4-28ec-42a1-8704-4e4aa51006b4",
  #       "issued": "2021-08-31T00:00:00Z",
  #       "issuer": "did:ebsi:2A9BZ9SUe6BatacSpvs1V5CdjHvLpQ7bEsi2Jb6LdHKnQxaN",
  #       "validFrom": "2021-08-31T00:00:00Z",
  #       "issuanceDate": "2021-08-31T00:00:00Z",
  #       "type": [
  #           "VerifiableCredential",
  #           "SomwareActivationService"
  #       ]
  #     }
